name: fruit_classifier
description: "A Flutter app that classifies fruits using TensorFlow Lite"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ML & Image Packages
  tflite_flutter: ^0.10.4
  # tflite_flutter_helper is not needed for basic TFLite functionality
  image_picker: ^1.0.8
  image: ^4.1.7
  
  # Required for state management and utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt

  # Enable AndroidX
  module:
    androidX: true