name: fruit_classifier
description: "A Flutter app that classifies fruits using TensorFlow Lite"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  tflite_flutter: ^0.10.4
  image_picker: ^1.0.8
  image: ^4.1.7
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  # Enable AndroidX
  module:
    androidX: true